name: Release Helpers

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-1
        with:
          config: cliff.toml
          args: -v

      - name: Generate a changelog for helpers
        uses: orhun/git-cliff-action@v3
        id: git-cliff-2
        with:
          config: cliff.toml
          args: -v --include-path "helpers/*"
