name: Release Helpers


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-1
        with:
          config: cliff.toml
          args: -v --latest --include-path
        env:
          OUTPUT: CHANGES1.md